name: Auto Label

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:

      # 根据标题打标签
      - name: Auto Label by Title
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            ${{ contains(github.event.issue.title, '[Bug]') && 'bug' || '' }}
            ${{ contains(github.event.issue.title, '[Feature]') && 'enhancement' || '' }}

      # PR默认打pr标签
      - name: Label PR
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: pr

      # 根据修改路径判断
      - name: Label by Path
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - 'src-tauri/**'
            frontend:
              - 'src/**'

      - name: Add Rust Label
        if: steps.changes.outputs.rust == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: rust

      - name: Add Frontend Label
        if: steps.changes.outputs.frontend == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: frontend